<?php

namespace FDA\RessourceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResCategRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResCategRepository extends EntityRepository
{
}
